import React, { useState, useEffect } from 'react';
import { Search, Trash2, AlertTriangle, X, Plus, Minus } from 'lucide-react';

interface RecipeRemovalProps {
  instancePath: string;
  onClose: () => void;
}

interface RecipeToRemove {
  id: string;
  type: string;
  file: string;
}

interface RemovalFilter {
  id: string;
  type: 'id' | 'output' | 'input' | 'mod' | 'type' | 'not';
  value: string;
}

export const RecipeRemoval: React.FC<RecipeRemovalProps> = ({ instancePath, onClose }) => {
  const [filters, setFilters] = useState<RemovalFilter[]>([
    { id: '1', type: 'output', value: '' }
  ]);
  const [recipesToRemove, setRecipesToRemove] = useState<RecipeToRemove[]>([]);
  const [selectedRecipes, setSelectedRecipes] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(false);
  const [previewCode, setPreviewCode] = useState('');

  const filterTypes = [
    { value: 'id', label: 'Recipe ID' },
    { value: 'output', label: 'Output' },
    { value: 'input', label: 'Input' },
    { value: 'mod', label: 'Mod' },
    { value: 'type', label: 'Recipe Type' },
  ];

  const addFilter = () => {
    setFilters([...filters, { 
      id: Date.now().toString(), 
      type: 'output', 
      value: '' 
    }]);
  };

  const removeFilter = (id: string) => {
    if (filters.length > 1) {
      setFilters(filters.filter(f => f.id !== id));
    }
  };

  const updateFilter = (id: string, field: 'type' | 'value', value: string) => {
    setFilters(filters.map(f => 
      f.id === id ? { ...f, [field]: value } : f
    ));
  };

  useEffect(() => {
    updatePreview();
  }, [filters]);

  const updatePreview = () => {
    const code = generateRemovalScript();
    setPreviewCode(code);
  };

  const generateRemovalScript = (): string => {
    const lines = [
      '// Recipe removals generated by MCED',
      "ServerEvents.recipes(event => {",
    ];

    // Build filter object
    const validFilters = filters.filter(f => f.value.trim() !== '');
    
    if (validFilters.length === 0) {
      lines.push('  // No filters specified');
    } else if (validFilters.length === 1) {
      const filter = validFilters[0];
      lines.push(`  event.remove({ ${filter.type}: '${filter.value}' });`);
    } else {
      // Multiple filters - create object
      const filterObj = validFilters.map(f => `${f.type}: '${f.value}'`).join(', ');
      lines.push(`  event.remove({ ${filterObj} });`);
    }

    lines.push("});");
    return lines.join('\n');
  };

  const handleApplyRemoval = async () => {
    const validFilters = filters.filter(f => f.value.trim() !== '');
    if (validFilters.length === 0) {
      alert('Please specify at least one filter');
      return;
    }

    try {
      const script = generateRemovalScript();
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `recipe_removals_${timestamp}.js`;
      
      await window.api.kubeJSSaveRecipe(instancePath, { filename, script });
      alert(`Recipe removal script saved: ${filename}`);
      onClose();
    } catch (error) {
      console.error('Failed to save removal script:', error);
      alert('Failed to save removal script');
    }
  };

  return (
    <div className="p-4 h-full flex flex-col bg-background">
      {/* Header */}
      <div className="flex items-center justify-between mb-4 pb-3 border-b border-border">
        <h2 className="text-xl font-semibold text-foreground">Remove Recipes</h2>
        <button 
          onClick={onClose}
          className="p-1.5 hover:bg-secondary rounded transition-colors"
        >
          <X className="w-5 h-5 text-muted-foreground" />
        </button>
      </div>

      <div className="flex-1 flex gap-4 min-h-0">
        {/* Left: Filter Builder */}
        <div className="flex-1 flex flex-col min-w-0">
          <div className="mb-3">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-sm font-medium text-foreground">Removal Filters</h3>
              <button 
                onClick={addFilter}
                className="px-2 py-1 bg-primary text-primary-foreground rounded text-xs font-medium hover:bg-primary/90 transition-colors flex items-center gap-1"
              >
                <Plus className="w-3 h-3" />
                Add Filter
              </button>
            </div>
            
            <div className="bg-muted/50 border border-border rounded p-2 mb-3">
              <p className="text-xs text-muted-foreground">
                Build your recipe removal filters. Use tags with # prefix (e.g., #minecraft:wool).
                Multiple filters are combined with AND logic.
              </p>
            </div>
          </div>

          {/* Filters */}
          <div className="flex-1 overflow-y-auto space-y-2 pr-1">
            {filters.map((filter, index) => (
              <div key={filter.id} className="flex gap-2 items-start bg-secondary/50 p-3 rounded border border-border">
                <div className="flex-1 space-y-2">
                  <select
                    value={filter.type}
                    onChange={(e) => updateFilter(filter.id, 'type', e.target.value)}
                    className="w-full px-2 py-1.5 bg-background border border-border rounded text-sm text-foreground focus:outline-none focus:border-primary"
                  >
                    {filterTypes.map(ft => (
                      <option key={ft.value} value={ft.value}>{ft.label}</option>
                    ))}
                  </select>
                  
                  <input
                    type="text"
                    value={filter.value}
                    onChange={(e) => updateFilter(filter.id, 'value', e.target.value)}
                    placeholder={
                      filter.type === 'id' ? 'minecraft:stone' :
                      filter.type === 'output' ? 'minecraft:stone or #minecraft:wool' :
                      filter.type === 'input' ? 'minecraft:iron_ingot or #forge:ingots/iron' :
                      filter.type === 'mod' ? 'minecraft' :
                      filter.type === 'type' ? 'minecraft:crafting_shaped' :
                      'Enter value...'
                    }
                    className="w-full px-2 py-1.5 bg-background border border-border rounded text-sm text-foreground placeholder-muted-foreground focus:outline-none focus:border-primary"
                  />
                </div>
                
                {filters.length > 1 && (
                  <button
                    onClick={() => removeFilter(filter.id)}
                    className="p-1.5 text-destructive hover:bg-destructive/10 rounded transition-colors"
                  >
                    <Minus className="w-4 h-4" />
                  </button>
                )}
              </div>
            ))}
          </div>

          {/* Warning */}
          <div className="mt-3 flex items-start gap-2 text-xs bg-amber-500/10 border border-amber-500/30 rounded p-2">
            <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
            <p className="text-amber-600 dark:text-amber-400">
              Recipe removals are permanent. A script will be created in server_scripts/ that will remove matching recipes when the game loads.
            </p>
          </div>
        </div>

        {/* Right: Code Preview */}
        <div className="flex-1 flex flex-col min-w-0">
          <h3 className="text-sm font-medium text-foreground mb-2">Generated Code Preview</h3>
          <div className="flex-1 bg-secondary/30 border border-border rounded p-3 overflow-auto">
            <pre className="text-xs text-foreground font-mono whitespace-pre-wrap">
              {previewCode || '// Configure filters to see preview...'}
            </pre>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-2 mt-4 pt-3 border-t border-border">
        <button 
          onClick={onClose}
          className="px-4 py-2 bg-secondary text-foreground rounded text-sm font-medium hover:bg-secondary/80 transition-colors"
        >
          Cancel
        </button>
        <button 
          onClick={handleApplyRemoval}
          disabled={filters.every(f => !f.value.trim())}
          className="px-4 py-2 bg-destructive text-destructive-foreground rounded text-sm font-medium hover:bg-destructive/90 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center gap-2"
        >
          <Trash2 className="w-4 h-4" />
          Create Removal Script
        </button>
      </div>
    </div>
  );
};
